version: '3.8'

services:
  hermes-1:
    build: 
      context: /Users/pedromedina/Documents/projetos/go/hermes-broker
    image: hermes-broker:latest
    hostname: hermes-1
    container_name: hermes-1
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      - HERMES_NODE_ID=hermes-1
      - HERMES_BUFFER_SIZE=20000
      - HERMES_RAFT_PORT=hermes-1.hermes-internal:6000 
      - HERMES_GRPC_PORT=:50051
      - HERMES_HTTP_PORT=:8080
      - HERMES_BOOTSTRAP=true
    volumes:
      - ./data/node-1:/root/data
    networks:
      hermes-net:
        aliases:
          - hermes-1.hermes-internal

  hermes-2:
    image: hermes-broker:latest
    depends_on:
      - hermes-1
    hostname: hermes-2
    container_name: hermes-2
    ports:
      - "50052:50051"
      - "8081:8080"
    environment:
      - HERMES_NODE_ID=hermes-2
      - HERMES_BUFFER_SIZE=20000
      - HERMES_RAFT_PORT=hermes-2.hermes-internal:6000
      - HERMES_GRPC_PORT=:50051
      - HERMES_HTTP_PORT=:8080
      - HERMES_BOOTSTRAP=false
      - HERMES_JOIN_ADDR=hermes-1.hermes-internal:8080
    volumes:
      - ./data/node-2:/root/data
    networks:
      hermes-net:
        aliases:
          - hermes-2.hermes-internal

  hermes-3:
    image: hermes-broker:latest
    depends_on:
      - hermes-1
    hostname: hermes-3
    container_name: hermes-3
    ports:
      - "50053:50051"
      - "8082:8080"
    environment:
      - HERMES_NODE_ID=hermes-3
      - HERMES_BUFFER_SIZE=20000
      - HERMES_RAFT_PORT=hermes-3.hermes-internal:6000
      - HERMES_GRPC_PORT=:50051
      - HERMES_HTTP_PORT=:8080
      - HERMES_BOOTSTRAP=false
      - HERMES_JOIN_ADDR=hermes-1.hermes-internal:8080
    volumes:
      - ./data/node-3:/root/data
    networks:
      hermes-net:
        aliases:
          - hermes-3.hermes-internal

networks:
  hermes-net:
    driver: bridge