services:
  hermes-1:
    build: .
    hostname: hermes-1
    container_name: hermes-1
    ports:
      - "50051:50051" # gRPC Host
      - "8080:8080"   # HTTP Host
    environment:
      - HERMES_NODE_ID=node-1
      - HERMES_BUFFER_SIZE=20000
      - HERMES_RAFT_PORT=hermes-1:6000
      - HERMES_GRPC_PORT=:50051
      - HERMES_HTTP_PORT=:8080
      - HERMES_BOOTSTRAP=true  # <--- O LÍDER SUPREMO NASCE AQUI
    volumes:
      - ./data/node-1:/root/data # Persistência
    networks:
      - hermes-net

  hermes-2:
    build: .
    hostname: hermes-2
    container_name: hermes-2
    ports:
      - "50052:50051" # Mapeia 50052 do host para 50051 do container
      - "8081:8080"
    environment:
      - HERMES_NODE_ID=node-2
      - HERMES_BUFFER_SIZE=20000
      - HERMES_RAFT_PORT=hermes-2:6000
      - HERMES_GRPC_PORT=:50051
      - HERMES_HTTP_PORT=:8080
      - HERMES_BOOTSTRAP=false # <--- Seguidor, espera convite
      - HERMES_JOIN_ADDR=hermes-1:8080
    volumes:
      - ./data/node-2:/root/data
    networks:
      - hermes-net

  hermes-3:
    build: .
    hostname: hermes-3
    container_name: hermes-3
    ports:
      - "50053:50051"
      - "8082:8080"
    environment:
      - HERMES_NODE_ID=node-3
      - HERMES_BUFFER_SIZE=20000
      - HERMES_RAFT_PORT=hermes-3:6000
      - HERMES_GRPC_PORT=:50051
      - HERMES_HTTP_PORT=:8080
      - HERMES_BOOTSTRAP=false
      - HERMES_JOIN_ADDR=hermes-1:8080
    volumes:
      - ./data/node-3:/root/data
    networks:
      - hermes-net

networks:
  hermes-net:
    driver: bridge